title: OKCLugNuts
description: >
  Oklahoma City Linux User Group
location: >
  StarSpace46 1141 W Sheridan Ave, 
  Oklahoma City, OK 73106
meetup: OKC-LUGnuts
location-map:
paginate: 3
plugins:
  - jekyll-paginate